include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = LunarCalendar

LunarCalendar_OBJC_FILES = \
	main.m \
	LunarCalendarDate.m \
	CalendarView.m

LunarCalendar_HEADERS = \
	LunarCalendarDate.h \
	CalendarView.h

LunarCalendar_RESOURCE_FILES = LunarCalendar.gorm

LunarCalendar_MAIN_MODEL_FILE = LunarCalendar.gorm

include $(GNUSTEP_MAKEFILES)/application.make
