include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = Search

Search_OBJC_FILES = \
	main.m \
	Controller.m 

Search_HEADERS = \
	Controller.h 

Search_RESOURCE_FILES = Search.gorm

Search_MAIN_MODEL_FILE = Search.gorm

include $(GNUSTEP_MAKEFILES)/application.make
