#
# Copyright © 2014 myOS Group.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# Contributor(s):
# Amr Aboelela <amraboelela@gmail.com>
#

CFLAGS=-DDEBUG
LDLIBS=-lCoreFoundation -lFoundation -lIOKit -lOpenGLES -lCoreGraphics -lCoreText
LIB_NAME=CoreAnimation

OBJECTS = \
    CAAnimation.o \
    CAGradientLayer.o \
    CAReplicatorLayer.o \
    CATiledLayer.o \
    CAValueFunction.o \
    CALayer.o \
    CALayer-CFunctions.o \
    CALayer+PresentationLayer.o \
    CARenderLayer.o \
    CALayerObserver.o \
    CAScrollLayer.o \
    CATransaction.o \
    CARenderer.o \
    CADisplayLink.o \
    CAMediaTiming.o \
    CAShapeLayer.o \
    CATransform3D.o \
    CAEAGLLayer.o \
    CAMediaTimingFunction.o \
    CATextLayer.o \
    CATransformLayer.o \
    CABackingStore.o \
    CAAnimator.o \
    CATransactionGroup.o \
    CACompositor.o \

include ${MYOS_PATH}/android/sdk/resources/makefile-shared
